// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/GetDatencoder.h"
#include "Commands/SetpointCommand1.h"
#include "Commands/pPushIn.h"
#include "Commands/pPushOut.h"
#include "Commands/sMoveServo.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	xBox = new Joystick(0);
	
	joystickButton4 = new JoystickButton(xBox, 4);
	joystickButton4->WhenPressed(new SetpointCommand1());
	joystickButton3 = new JoystickButton(xBox, 3);
	joystickButton3->WhenPressed(new GetDatencoder());
	joystickButton2 = new JoystickButton(xBox, 2);
	joystickButton2->WhenPressed(new pPushIn());
	joystickButton1 = new JoystickButton(xBox, 1);
	joystickButton1->WhenPressed(new sMoveServo());
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

	SmartDashboard::PutData("pPushOut", new pPushOut());

	SmartDashboard::PutData("pPushIn", new pPushIn());

	SmartDashboard::PutData("sMoveServo", new sMoveServo());

	SmartDashboard::PutData("GetDatencoder", new GetDatencoder());

	SmartDashboard::PutData("Setpoint Command 1", new SetpointCommand1());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getxBox() {
	return xBox;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
